name: "Build and Test"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.7"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.2.0"
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: |
          poetry install --no-interaction
      - name: Check formatting
        run: poetry run black --line-length 120 --check .
      - name: Run tests and generate coverage report
        run: poetry run pytest -s --junitxml=./test-report.xml --cov=./ --cov-report=xml .
      - uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: ./test-report.xml
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./coverage.xml
      #     flags: unittests
      #     name: codecov-umbrella
      #     fail_ci_if_error: true